select ANIMAL_OUTS.ANIMAL_ID as ANIMAL_ID,ANIMAL_OUTS.NAME as NAME 
from ANIMAL_OUTS left join ANIMAL_INS on ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
where ANIMAL_INS.ANIMAL_ID is null
order by animal_id,name;